apiVersion: v1
kind: Service
metadata:
  name: app-python
spec:
  type: {{ .Values.service.type }}
  selector:
    app: app-python
  ports:
    - port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.containerPort }}