image:
  repository: andreshr/app-python
  tag: "02cd14320130b8dceb483de823d66649087304cb"

imagePullSecrets:
  - name: dockerhub-secret

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP

ports:
  port: 80
  containerPort: 8000

replicaCount: 2