image:
  repository: andresfhr/app-python
  tag: "latest"

imagePullSecrets:
  - name: dockerhub-secret

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: ClusterIP

ports:
  port: 80
  containerPort: 8000

replicaCount: 1
label: "dev"
