name: app-python-cicd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: 3.14
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    # NUEVO: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # MODIFICADO: Construir y subir asegurando nombre de usuario en minúsculas
    - name: Build and push Docker image
      run: |
        DOCKER_USER=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
        docker build -t $DOCKER_USER/app-python:latest .
        docker push $DOCKER_USER/app-python:latest
