name: cd-prd

on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Update Helm values-prd.yaml and Push to GitHub
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
         
        sed -i 's/tag: .*/tag: "${{ github.sha }}"/' charts/app-python/values-prd.yaml
 
        git add charts/app-python/values-prd.yaml
        git commit -m "CD: Update image tag to ${{ github.sha }} [skip ci]"
        
        git push -u origin main